name: Tests and Code Checks

on: [pull_request]

jobs:
  verify-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        run: "cat hub.json | python3 -m json.tool"

  code-quality:
    name: code-quality

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.9'

      - name: Install python dependencies
        run: |
          python -m pip install --user --upgrade pip
          python -m pip --version
          python -m pip install pre-commit
          pre-commit --version
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
